### ISSUE TITLE
Request for Setup Instructions

### ISSUE THREAD

**Issue by lovelindhoni** [stdlib-js/www#64]
Could someone please provide detailed instructions on how to set up the environment and start hacking on the site locally? 
Any guidance would be greatly appreciated.

@kgryte  @Planeshifter

**Comment by kgryte** [comment]
I suggest exploring the repo: https://github.com/stdlib-js/www/blob/master/docs/build.md

**Comment by lovelindhoni** [comment]
I set it up just as directed in the build instructions above, but for some reason, I can't build api-docs-app (using make api-docs-app).

```bash
Setting NODE_PATH to resolve modules absolutely has been deprecated in favor of setting baseUrl in jsconfig.json (or tsconfig.json if you are using TypeScript) and will be removed in a future major release of create-react-app.

Creating an optimized production build...
Error parsing bundle asset "/home/lovelindhoni/dev/projects/www/public/docs/api/static/js/2.e5556929.chunk.js": no such file
Error parsing bundle asset "/home/lovelindhoni/dev/projects/www/public/docs/api/static/js/main.9ba952b5.chunk.js": no such file
Error parsing bundle asset "/home/lovelindhoni/dev/projects/www/public/docs/api/static/js/runtime-main.e47de42b.js": no such file

No bundles were parsed. Analyzer will show only original module sizes from stats file.

Webpack Bundle Analyzer saved report to /home/lovelindhoni/dev/projects/www/build/bundle_report.html
Failed to compile.

Failed to minify the bundle. Error: static/js/main.9ba952b5.chunk.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at Array.forEach (<anonymous>)
    at /home/lovelindhoni/dev/projects/www/tools/scripts/api-docs/app.js:152:19
    at finalCallback (/home/lovelindhoni/dev/projects/www/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/lovelindhoni/dev/projects/www/node_modules/webpack/lib/Compiler.js:273:13
    at eval (eval at create (/home/lovelindhoni/dev/projects/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at Immediate.<anonymous> (/home/lovelindhoni/dev/projects/www/node_modules/webpack-bundle-analyzer/lib/BundleAnalyzerPlugin.js:75:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Read more here: https://bit.ly/CRA-build-minify

make: *** [/home/lovelindhoni/dev/projects/www/tools/make/lib/docs/app.mk:34: api-docs-app] Error 1
```

**Comment by kgryte** [comment]
What version of Node.js and npm are you using?

**Comment by kgryte** [comment]
...and what happens when you just run

```bash
make build
```

?

**Comment by lovelindhoni** [comment]
Everything works fine when I downgraded my node version from 20.11.1 to 16.20.2 (lts/gallium) :)

**Comment by kgryte** [comment]
Hmm...interesting. Thanks for that info.

cc @Planeshifter

**Comment by krishnaagrawal7508** [comment]
I set it up just as directed in the build instructions above, but for some reason, when I run make (make build) then no response is shown...

![Screenshot 2024-03-22 005416](https://github.com/stdlib-js/www/assets/120992509/ef36264d-0aed-4ce1-a4d8-601392163519)

**Comment by kgryte** [comment]
You can try running the various steps executed by `make build` individually. You can find those in the make files present in this repo.

**Comment by gcbibek3353** [comment]
@kgryte I tried to set up the project locally by following  www/docs/build.md file instructions.
I am getting this error on executing 
make build and npm run start
can you help me with this issue ? 

![Image](https://github.com/user-attachments/assets/5b8f7bb3-1bed-4b7b-bea3-fb2316694365)

![Image](https://github.com/user-attachments/assets/1a2d4e99-6269-4927-af02-ff5a3eec823d)

**Comment by kgryte** [comment]
@gcbibek3353 Did you run `make install` beforehand?

**Comment by Girish-Garg** [comment]
![Image](https://github.com/user-attachments/assets/4d013903-5d24-46c9-810a-a97785c5b72f)

I have checked whole `@stdlib` in `node_modules` and unable to fine `_tools` which is causing error i think 
`fs/exists` and `process/cwd` exists but `_tools/docs/www/benchmark-bundles` is not even installing from npm separately

![Image](https://github.com/user-attachments/assets/16379336-e777-4abf-980c-1889f202dd8b)

**Comment by kgryte** [comment]
First run

```
make install
```

then check the root `node_modules` directory in the cloned `www` repository on your local machine. You should see a `@stdlib/stdlib` package installed. If you do not, something is messing up with the clone command (see https://github.com/stdlib-js/www/blob/master/tools/make/lib/install/node.mk#L41).

If it is there, it is possible that the `NODE_PATH` environment variable is not being handled correctly. If so, what is your Node version and npm version?

**Comment by Girish-Garg** [comment]
@kgryte did the whole `make install` again and got all the `@stdlib/_tools` now but there is still some error with build function as it is causing in sleep which i conformed after running process status command --->

![Image](https://github.com/user-attachments/assets/43ef7241-c708-4e52-a781-713cda6dfc75)


![Image](https://github.com/user-attachments/assets/d169023f-3dbf-4e0d-aaae-353f26f1d4be)

node --> v22.14.0 (lts/jod)
npm --> 11.2.0

**Comment by kgryte** [comment]
@Girish-Garg One question. Why are you needing to run `make pkg-benchmarks`? If you are just needing to rebuild the docs site, you only need to run the relevant commands for regenerating the React app. When you run `make pkg-benchmarks`, you are very likely to not see anything printed and the process can take well over an hour. If you want to verify that things are actually happening in the background, set `DEBUG=*` when running that command. We intentionally don't print anything to the terminal in order to avoid printing walls of text.
